---
variables:
  # BASIC SETTINGS
  # language, identifies the main language of the document, (polyglossia-lang)
  # default: 'en'
  lang: 'en'
  
  # the base direction of the document, either rtl (right-to-left) or ltr
  # (left-to-right). When using LaTeX for bidirectional documents, only the
  # xelatex engine is fully supported (use --pdf-engine=xelatex).
  # default: 'ltr'
  dir: 'ltr'
  
  # paper size, e.g. letter, a4
  # default: 'a4'
  papersize: 'a4'
  
  # font size for body text (e.g. 10pt, 12pt)
  # default: '11pt'
  fontsize: '11pt'
  
  # document class, e.g. article, report, book, memoir, scrreport, scrartcl,
  # default: 'scrbook'
  # DO NOT CHANGE THIS OPTION!
  documentclass: 'scrbook'
  
  # option for document class, e.g. titlepage, oneside; may be repeated for
  # multiple options.
  # some exmaple options:
  #  11pt,%-------------------------------to have a document with font size: 11pt
  #  paper=a4,%-----------------------to have a document with real paper size: a4
  #  pagesize,%-------to have a virtual page size that is equal to the paper size
  #  twoside,%--------------------------------to print on both sides of the paper
  #  %oneside,%------------------to “print” just on one side of digitaly pdf page
  #  BCOR=2mm,%---------------------------------to reserve 2mm binding correction
  #  openright,%---------------------------to open new chapters on the right side
  #  titlepage=firstiscover%----to specifie the first page as a cover/ image page
  # ]{scrbook}%----------------------------to use the koma-script class "scrbook"
  # defaults:
  #  - 'twoside'
  #  - 'twocolumn'
  #  - 'parskip=full'
  classoption:
    - 'twoside'
    - 'onecolumn'
  #  - 'twocolumn'
  
  # TITLEPAGE(S) SETTINGS
  # to omit the default title pages and specify your own titlepage layout in
  # ./controls/arabica.latex
  # default: false
  custom_title_page: false
  
  # to have a half title (page)
  # default: true
  extratitle: true
  
  # to have additional information (advisors name, …) in the publishers field
  # this option needs extratitile to be true
  # EITER both false OR only one is true (NOT both can be true)
  # default: true
  title_page_a: true
  # default: false
  title_page_b: false
  
  # give path here if you want to include a logo or graphic in your title page(s)
  # example: './titlepage/dummygraphic.pdf'
  titlepage:
    graphic: #'./graphics/dummygraphic.pdf'
    logo: #'./graphics/dummylogo.pdf'
  
  # activate / deactivate display of your abtsract text
  # the classoption "abstract" only specifies if the (language dependent) heading
  # "Abstract" is displayed or not.
  # default: true
  display_abstract: true
  
  # include table of contents (can also be set using --toc/--table-of-contents)
  # default: true
  toc: true
  
  # if you want to have a onecolumn table of content even if your document is
  # in twocolumn,then set this option to true.
  # if true, loading pkg "multicol" is mandatory
  # default: false
  onecol_toc: false
  
  # level of section to include in table of contents
  # default: 2
  toc-depth: 2
  
  # DEFAULT PACKAGES
  # option for geometry package, e.g. margin=1in; may be repeated for multiple
  # options
  # default:
  geometry:
  
  # sets margins, if geometry is not used (otherwise geometry overrides these)
  # default:
  margin-left:
  margin-right:
  margin-top:
  margin-bottom:
  
  # adjusts line spacing using the setspace package, e.g. 1.25, 1.5
  # default:
  linestretch:
  
  # font package for use with pdflatex; TeX Live includes many options,
  # documented in the LaTeX Font Catalogue. The default is Latin Modern.
  # default: 'libertine'
  fontfamily: 'libertine'
  
  # options for package used as fontfamily; e.g. osf,sc with fontfamily set to
  # mathpazo provides Palatino with old-style figures and true small caps; may be
  # repeated for multiple options
  # default:
  fontfamilyoptions:
  
  # advanced font selection in XeLaTeX and LuaLaTeX
  # enable system font access (needed by XeLaTex)
  # for: \setmainfont{...}, \setsansfont{...}, \setmonofont{...}
  # and  \setmathfont{...} see option "mainfont".
  # default: true
  fontspec: true
  
  # font families for use with XeLaTeX or LuaLaTeX take the name of any system
  # font, using the fontspec package. Note that if CJKmainfont is used, the xecjk
  # package must be available.
  mainfont: 'Libertinus Serif'
  sansfont: 'Libertinus Sans'
  monofont: 'Libertinus Mono'
  mathfont: 'Libertinus Math'
  CJKmainfont:
  
  # options to use with mainfont, sansfont, monofont, mathfont, CJKmainfont in
  # xelatex and lualatex. Allow for any choices available through fontspec, such # as the OpenType features Numbers=OldStyle,Numbers=Proportional. May be
  # repeated for multiple options.
  # default:
  mainfontoptions:
  sansfontoptions:
  monofontoptions:
  mathfontoptions:
  CJKoptions:
  
  # allows font encoding to be specified through fontenc package (with pdflatex); # default is T1 (see guide to LaTeX font encodings)
  # default:
  fontenc:
  
  # options to pass to the microtype package
  # the microtype package is loaded automatically if available
  # default: 'final'
  microtypeoptions: 'final'
  
  # add color to link text; automatically enabled if any of linkcolor, citecolor, # urlcolor, or toccolor are set (see pkg/ option "xcolor")
  # default: true
  colorlinks: true
  
  # color for internal links, citation links, external links, and links in table # of contents; uses options allowed by xcolor, including the dvipsnames,
  # svgnames, and x11names lists
  # default:
  linkcolor:
  citecolor:
  urlcolor:
  toccolor:
  
  # causes links to be printed as footnotes
  # default:
  links-as-notes:
  
  # EXTRA PACKAGES
  # to manage text 'layers' within koma-script
  # default:
  scrlayer:
  
  # to define and manage page styles (see "fancyhdr" too)
  # default:
  scrlayer-scrpage:
  
  # to control note columns parallel to the main text
  # to set side note column you need pkg "scrlayer-notecolumn"
  # you may want to set: \setkomafont{notecolumn.marginpar}{\footnotesize}
  # default:
  scrlayer-notecolumn:
  # default: '\footnotesize'
  notecolumnfontsize: '\footnotesize'
  
  # for url-sensitive linebreaks (needed by XeLaTex)
  # default:
  url:
  
  # for fitch-style natural deduction proofs
  # default:
  lplfitch:
  
  # for advanced math typesetting (loads all default math pkg)
  # if you set this option all the folowing packages will be loaded automatically
  # except for: package "amssymb" and "amsmath" because they are loaded
  # automatically.
  # mathematical tools to use with amsmath
  # \usepackage{mathtools}
  # ams mathematical facilities for LaTeX
  # \usepackage{amsmath}# possibly loaded loaded somewhere else too
  # TeX fonts from the american mathematical society
  #  \usepackage{amsfonts}
  # additional mathematical symbols
  # \usepackage{amssymb}# possibly loaded loaded somewhere else too
  # typesetting of custom theorems (in ams style)
  #  \usepackage{amsthm}
  # dirac bra-ket and set notations
  #  \usepackage{braket}
  # for numbered cases (mappings) environment
  #  \usepackage{cases}
  # for proof trees in the style of the sequent calculus
  #  \usepackage{bussproofs}
  # default: true
  math: true
  
  # to create (tabular cells spanning) multiple rows
  # default:
  multirow:
  
  # to create continuation headings and legends for floats
  # default:
  ccaption:
  
  # to inlcude images (.pdf, .eps, .png)
  # default: true
  graphics: true
  
  # to scale graphics relative to reference object (needs pkg "graphicx")
  # usage: \scalerel*{\includegraphics{inlinegraphic.pdf}}{O}
  # default: true
  scalerel: true
  
  # to allow text to flow around graphics
  # default:
  wrapfig:
  
  # to insert pictures into paragraphs (see pkg "picins")
  # default:
  picinpar:
  
  # for driver-independent color extensions (see option "colorlinks")
  # the package xcolor is loaded automatically if colorlinks are set
  # default:
  xcolor:
  # default: 'usenames'
  xcoloroptions: 'usenames'
  
  # to create postscript and pdf graphics in TeX (see pkg "tikz")
  # default:
  pgf:
  
  # for drawing functions in LaTeX
  # you may want to use specific tikz libraries e.g.:
  # \usetikzlibrary{shapes,arrows,chains,positioning,fit,automata}
  # default:
  tikz:
  # default:
  usetikzlibrary:
  
  # to not interpret latex commands but display them (see pkg "upquote")
  # default:
  verbatim:
  
  # to typeset dropped capitals
  # default:
  lettrine:
  
  # to avoid widows
  # default: true
  nowidow: true
  # default:
  #  - 'defaultlines=3'
  #  - 'all'
  nowidowoptions:
  
  # to generate lorem ipsum blind text text for testing purposes
  # default:
  blindtext:
  
  # to generate sentences in kant's style for testing purposes
  # default:
  kantlipsum:
  
  # to draw frame around pages to see margin changes for testing purposes
  # default:
  showframe:
  
  # to print watermarks
  # firstpage to put a watermark text only on the first page
  # nostamp for quickly removing the “draft” status from a document
  # default:
  draftwatermark:
  # default:
  #  - 'firstpage'
  #  - 'nostamp'
  #  - 'titlepage'
  draftwatermarkoptions:
    - 'firstpage'
    - 'nostamp'
    - 'titlepage'
  
  # set pagestyle (needs pkg "scrlayer-scrpage")
  # default:
  scrheadings:
  
  # float (load pkg "float" before pkg "hyperref")
  # default:
  float:
  
  # DEFAULT SETTINGS
  # uses document class settings for indentation (the default LaTeX template
  # otherwise removes indentation and adds space between paragraphs)
  # default:
  indent: true
  
  # disables default behavior of LaTeX template that redefines (sub)paragraphs as
  # sections, changing the appearance of nested headings in some classes
  # default:
  subparagraph:
  
  # numbering depth for sections, if sections are numbered
  # default: 3
  secnumdepth: 3
  
  # include list of figures, list of tables
  # default: false
  lof: false
  # default: false
  lot: false
  
  # to activate numbered sections (headdings)
  # default: true
  number-sections: true
  
  # an option for LaTeX’s \pagestyle{}. The default article class supports
  # ‘plain’ (default), ‘empty’, and ‘headings’; headings puts section titles in
  # the header.
  # default: 'headings'
  pagestyle: 'headings'
  
  # pandoc-citeproc citation style
  # default: './csl/chicago-author-date-de.csl'
  csl: './csl/chicago-author-date-de.csl'
  
  # pandoc-citeproc
  # default: true
  link-citations: true
  
  # bibliographic database
  bibliography: './bib/references.bib'
  # if you want to print out all items in your bibliography file regardles of
  # you mentioned them in your project, then uncomment the following 2 lines.
  # default: # (commented out)
  nocite: |
    @*
  
  # if you want to have a custom title for your bibliography specify it here
  # default:
  reference-section-title:
  
  # bibliography style, when used with --natbib and --biblatex.
  # default:
  biblio-style:
  
  # bibliography title, when used with --natbib and --biblatex.
  # default:
  biblio-title:
  
  # list of options for biblatex.
  # default:
  biblatexoptions:
  
  # list of options for natbib.
  # default:
  natbiboptions:
  
  # EXTRA SETTINGS
  # for creative commons icons
  # default: true
  ccicons: true
  
  # to inject hyperref compatible metadata into the pdf
  # default:
  hyperxmp:
  
  # to mix onecolumn and twocolumn modes for example for wide equations.
  # usage: \begin{strip}...\end{strip}
  # default: true
  cuted: true
  
  # to create (tabular cells spanning) multiple columns
  # default: true
  multicol: true
  
  # typographical intervention aka matter of taste: set this to true if you want
  # to use one and only one single font (typeface) for the entire document
  # including headings.
  # (komascript uses bold sans font for headings per default which is not optimal # IMO.)
  # default: true
  serif_headings: true
...