################
# Everyday
################
[[templates]]
description = "The Markdown resume, HTML version."
license = { name = "CC BY-SA 3.0", url = "https://creativecommons.org/licenses/by-sa/3.0/deed.en_US", repository_url = "https://github.com/mszep/pandoc_resume" }
contents_file = "include_in_header/resume.css.html"


################
# Professional/Academic
################
# TODO: convert fonts in variables
# TODO: a lot of problems (rare packages and chapters decorations don't work)
[[templates]]
description = "A template for creating a PhD thesis in Pandoc."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/chiakaivalya/thesis-markdown-pandoc" }
contents_file = "include_in_header/thesis_markdown.latex"

[[templates]]
description = "Template for PhD thesis used for submission to University College London."
license = { name = "MIT", url = "https://github.com/tompollard/phd_thesis_markdown/blob/master/LICENSE", repository_url = "https://github.com/tompollard/phd_thesis_markdown" }
contents_file = "include_in_header/ucl_phd_thesis_preamble.latex"
[[templates]]
description = "Template for PhD thesis used for submission to University College London."
license = { name = "MIT", url = "https://github.com/tompollard/phd_thesis_markdown/blob/master/LICENSE", repository_url = "https://github.com/tompollard/phd_thesis_markdown" }
contents_file = "include_in_header/ucl_phd_thesis.css.html"


# https://github.com/cagix/pandoc-lecture (exam, homework and lecture)
[[templates]]
description = "Template for exams."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "include_in_header/exam_homework_lecture_definitions.latex"
[[templates]]
description = "Template for lecture slides."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "include_in_header/lecture_beamer.latex"