# https://github.com/cagix/pandoc-lecture (exam, homework and lecture)
[[templates]]
description = "Template for exams."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "include_after_body/exam_end.latex"