[[templates]]
description = "Add `target=\"_blank\"` attributes to all http(s) links."
license = { name = "CC BY-SA 3.0", url = "https://creativecommons.org/licenses/by-sa/3.0/deed.en_US", repository_url = "https://github.com/mszep/pandoc_resume" }
contents_file = "lua_filters/add_target_blank.lua"

# pandoc_lecture custom filters
[[templates]]
description = "Add points to homework reading metadata."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_addpoints.lua"
[[templates]]
description = "Process blue arrows."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_blueArrow.lua"
[[templates]]
description = "Issue a warning if `cbox` spans are used instead of `::: cbox ... :::`."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_deprecated.lua"
[[templates]]
description = "Exams custom filter."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_exams.lua"
[[templates]]
description = "Extract title from metadata block and all headings."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_extract_filewise.lua"
[[templates]]
description = "Extract summary from lectures in the correct format."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_extract_summary.lua"
[[templates]]
description = "Translate ISBN links generated by citeproc (needs to be run after citeproc)."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_fhbib.lua"
[[templates]]
description = "Add LaTeX code to headers with `{punkte=42}`."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_headertotask.lua"
[[templates]]
description = "Add HOME-Button if MetaString/MetaInlines 'home' is present, inject a block (para) containing a link to the URI in meta.home."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_home.lua"
[[templates]]
description = "Custom Lua filter for Hugo lecture template."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_hugo.lua"
[[templates]]
description = "LaTeX `codeblock`s for listings."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_listings.lua"
[[templates]]
description = "Prepare handout in lecture template."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_prepareHandout.lua"
[[templates]]
description = "Prepare Beamer slides in lecture template."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_prepareSlides.lua"
[[templates]]
description = "Custom Lua filter for homework questions."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_questions.lua"
[[templates]]
description = "Custom Lua filter for preparing toggle elements in HTML handouts."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_showme.lua"
[[templates]]
description = "Strip image size attributes."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_stripImageAttrs.lua"
[[templates]]
description = "Custom Lua filter for TeX output pandoc_lecture templates."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "lua_filters/pandoc_lecture_tex.lua"

# end of pandoc_lecture custom filters

[[templates]]
description = "A pandoc Lua filter for linguistic examples."
license = { name = "CC0 1.0", url = "https://github.com/cysouw/pandoc-ling/blob/main/LICENSE", repository_url = "https://github.com/cysouw/pandoc-ling" }
contents_file = "lua_filters/pandoc-ling.lua"

[[templates]]
description = "A pandoc Lua filter to include files inside code blocks."
license = { name = "MIT", url = "https://github.com/averms/pandoc-filters/blob/master/LICENSE.md", repository_url = "https://github.com/averms/pandoc-filters#code-includes" }
contents_file = "lua_filters/code-includes.lua"

# https://github.com/averms/pandoc-filters/blob/master/src/transclude.lua
# recommends to use the include-files Lua filter instead

# https://github.com/cysouw/count-para 1.2 version is not ready yet and it does
# not seems very useful

[[templates]]
description = "A pandoc Lua filter to provide multicolumn support."
license = { name = "MIT", url = "https://github.com/dialoa/columns/blob/master/LICENSE", repository_url = "https://github.com/dialoa/columns" } 
contents_file = "lua_filters/columns.lua"

[[templates]]
description = "A pandoc Lua filter to add table of contents to the side in HTML."
license = { name = "CC0-1.0", url = "https://github.com/cysouw/toc-css/blob/main/LICENSE", repository_url = "https://github.com/cysouw/toc-css" } 
contents_file = "lua_filters/toc-css.lua"

# https://github.com/pandoc/lua-filters
[[templates]]
description = "A pandoc Lua filter to move a section in the body with id `abstract` to the metadata."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/abstract-to-meta.lua"

[[templates]]
description = "A pandoc Lua filter to add author-related header blocks. It must be executed after `scholarly-metadata` Lua filter."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/author-info-blocks.lua"

[[templates]]
description = "A pandoc Lua filter to export all cited references to a single bibtex file."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/bibexport.lua"

[[templates]]
description = "A pandoc Lua filter to extract optional CiTO information into the metadata. It must be executed before citeproc."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/cito.lua"

[[templates]]
description = "A pandoc Lua filter to create images from PlantUML, Graphviz, TikZ and Python code blocks. The external tools must be installed."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/diagram-generator.lua"

[[templates]]
description = "A pandoc Lua filter to include code files in code blocks."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/include-code-files.lua"

[[templates]]
description = "A pandoc Lua filter to include text files using code blocks with class `include`."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/include-files.lua"

[[templates]]
description = "A pandoc Lua filter to replace hyphens by LaTeX raw `\"=` expression for better hyphenation."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/latex-hyphen.lua"

[[templates]]
description = "A pandoc Lua filter to generate embedded images for music notation from LilyPond code."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/lilypond.lua"

[[templates]]
description = "A pandoc Lua filter to use the `minted` package in LaTeX and beamer code listings."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/minted.lua"

[[templates]]
description = "A pandoc Lua filter to create multiple bibliographies using citeproc."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/multiple-bibliographies.lua"

[[templates]]
description = "A pandoc Lua filter to convert LaTeX `pagebreak` and `newpage` commands into pagebreaks in other formats."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/pagebreak.lua"

[[templates]]
description = "A pandoc Lua filter that adapts quotation marks."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/pandoc-quotes.lua"

[[templates]]
description = "A pandoc Lua filter to enable Reveal JS code block features. It requires adding `highlight.js` to the template."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/revealjs-codeblock.lua"

[[templates]]
description = "A pandoc Lua filter to transform authors metadata into a canonical form."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/scholarly-metadata.lua"

[[templates]]
description = "A pandoc Lua filter to write DIN 5008 letters using scrlttr2 LaTeX document class from KOMA script."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/scrlttr2.lua"

[[templates]]
description = "A pandoc Lua filter to put bibliographies at the end of each section."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" } 
contents_file = "lua_filters/section-refs.lua"

[[templates]]
description = "Short captions in the list of figures of LaTeX output."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" }
contents_file = "lua_filters/short_captions.lua"

[[templates]]
description = "A Lua filter to check the spelling of words using the external program `aspell`."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" }
contents_file = "lua_filters/spellcheck.lua"

[[templates]]
description = "Short captions in the list of tables of LaTeX output. If pandoc-crossref is used, it should be run after this."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" }
contents_file = "lua_filters/table_short_captions.lua"

[[templates]]
description = "A Lua filter to track changes in LaTeX and HTML like in Word documents."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" }
contents_file = "lua_filters/track-changes.lua"

[[templates]]
description = "A Lua filter to count the words in the body of a document."
license = { name = "MIT", url = "https://github.com/pandoc/lua-filters/blob/master/LICENSE", repository_url = "https://github.com/pandoc/lua-filters" }
contents_file = "lua_filters/wordcount.lua"