################
# General
################
[[templates]]
description = "A simple annotated template."
license = { name = "UNLICENSE", url = "", repository_url = "https://gist.github.com/michaelt/1017790" }
contents_file = "latex/simple_annotated.latex"

[[templates]]
description = "The default template removing 'Figure #' automatic labels from caption."
license = { name = "UNLICENSE", url = "", repository_url = "https://gist.github.com/1366514" }
contents_file = "latex/no_numbered_captions.latex"

[[templates]]
description = "Minimal (designed to customize complete templates) template to customize tables using booktabs."
license = { name = "UNLICENSE", url = "", repository_url = "https://gist.github.com/jlduran/7786752" }
contents_file = "latex/minimal_booktabs.latex"


################
# Everyday
################
[[templates]]
description = "A clean pandoc LaTeX template for lecture notes and exercises with a focus on computer science."
license = { name = "BSD-3-Clause", url = "https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/LICENSE", repository_url = "https://github.com/Wandmalfarbe/pandoc-latex-template" }
contents_file = "latex/eisvogel.latex"

# https://github.com/aaronwolen/pandoc-letter cannot be included because it is GPL-3.0 licensed

[[templates]]
description = "Template for making Tufte-style handouts."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/wcaleb/pandoc-templates" }
contents_file = "latex/tufte_handouts.latex"

[[templates]]
description = "The Markdown resume. ConTeXt required."
license = { name = "CC BY-SA 3.0", url = "https://creativecommons.org/licenses/by-sa/3.0/deed.en_US", repository_url = "https://github.com/mszep/pandoc_resume" }
contents_file = "latex/resume.latex"

[[templates]]
description = "Beamer slides and handouts (use slide-level 2 and check https://gist.github.com/lmullen/c3d4c7883f081ed8692a#file-makefile for generating handouts)."
license = { name = "UNLICENSE", url = "", repository_url = "https://gist.github.com/lmullen/c3d4c7883f081ed8692a" }
contents_file = "latex/lmullen_slides_handouts.latex"


################
# Professional/Academic
################
# https://github.com/chiakaivalya/thesis-markdown-pandoc is not a template but uses preamble and csl

# TODO: UC logo as variable
[[templates]]
description = "Template for PhD thesis used for submission to University College London."
license = { name = "MIT", url = "https://github.com/tompollard/phd_thesis_markdown/blob/master/LICENSE", repository_url = "https://github.com/tompollard/phd_thesis_markdown" }
contents_file = "latex/ucl_phd_thesis.latex"
[[templates]]
description = "Template for PhD thesis used for submission to University College London."
license = { name = "MIT", url = "https://github.com/tompollard/phd_thesis_markdown/blob/master/LICENSE", repository_url = "https://github.com/tompollard/phd_thesis_markdown" }
contents_file = "html/ucl_phd_thesis.html"

# https://github.com/mabl/pandoc-thesis is not a template but just an example with custom stys and footers
# https://github.com/davecap/markdown-latex-boilerplate has GPL 3.0 license

[[templates]]
description = "Sound and versatile LaTeX template for academic articles."
license = { name = "MIT", url = "https://github.com/periodicpoint/robusta/blob/master/LICENSE.md", repository_url = "https://github.com/periodicpoint/robusta" }
contents_file = "latex/robusta.latex"
[[templates]]
description = "Sound and versatile LaTeX template for academic books."
license = { name = "MIT", url = "https://github.com/periodicpoint/arabica/blob/master/LICENSE.md", repository_url = "https://github.com/periodicpoint/arabica"}
contents_file = "latex/arabica.latex"

[[templates]]
description = "Simple APA 6 template. Requires APA 6 cls."
license = { name = "UNLICENSE", url = "", repository_url = "https://bitbucket.org/zuline/md2latex/src/master/" } 
contents_file = "latex/apa6.latex"

# https://github.com/juh2/pandoc-project-boilerplate is GPL 2.0 licensed
# https://github.com/jbn/paper is only a skeleton without template

# https://github.com/cagix/pandoc-lecture consists of
# exam, homework and lecture with complex builds
# TODO: translations using variables
# TODO: HTML lecture is a complex template that does not pay off now
[[templates]]
description = "Template for exams, some contents in German."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "latex/exam.latex"
[[templates]]
description = "MD intermediate template for homework, some contents in German."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "md/homework_questions.md"
[[templates]]
description = "Template for homework, some contents in German."
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "latex/homework.latex"


# Journal templates
[[templates]]
description = "AMSTAT journal."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/sachsmc/pandoc-journal-templates" }
contents_file = "latex/amstat.latex"
[[templates]]
description = "Biometrical journal."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/sachsmc/pandoc-journal-templates" }
contents_file = "latex/biometrical_journal.latex"
[[templates]]
description = "Biometrics journal."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/sachsmc/pandoc-journal-templates" }
contents_file = "latex/biometrics.latex"
[[templates]]
description = "Biometrika journal."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/sachsmc/pandoc-journal-templates" }
contents_file = "latex/biometrika.latex"
[[templates]]
description = "Biostatistics journal."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/sachsmc/pandoc-journal-templates" }
contents_file = "latex/biostatistics.latex"
[[templates]]
description = "IMS journal."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/sachsmc/pandoc-journal-templates" }
contents_file = "latex/ims.latex"
# JSS bst and cls files are GPL 2.0 licensed.
# [[templates]]
# description = "JSS journal."
# license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/sachsmc/pandoc-journal-templates" }
# contents_file = "latex/jss.latex"
[[templates]]
description = "Rjournal."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/sachsmc/pandoc-journal-templates" }
contents_file = "latex/rjournal.latex"
[[templates]]
description = "Stats in med journal."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/sachsmc/pandoc-journal-templates" }
contents_file = "latex/stats_in_med.latex"

# MLA templates
[[templates]]
description = "MLA-formatted PDFs."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/shushcat/mla_paper_template" }
contents_file = "latex/mla8.latex"
[[templates]]
description = "MLA-formatted opendocument."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/shushcat/mla_paper_template" }
contents_file = "opendocument/mla8.opendocument"
[[templates]]
description = "MLA-formatted roff."
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/shushcat/mla_paper_template" }
contents_file = "roff/mla8.roff"


################
# EPUB
################
[[templates]]
description = "Simple book template."
license = { name = "MIT", url = "https://github.com/wikiti/pandoc-book-template/blob/master/LICENSE.md", repository_url = "https://github.com/wikiti/pandoc-book-template" }
contents_file = "latex/simple_book.latex"
[[templates]]
description = "Simple book template."
license = { name = "MIT", url = "https://github.com/wikiti/pandoc-book-template/blob/master/LICENSE.md", repository_url = "https://github.com/wikiti/pandoc-book-template" }
contents_file = "epub/simple_book.epub"
[[templates]]
description = "Simple book template."
license = { name = "MIT", url = "https://github.com/wikiti/pandoc-book-template/blob/master/LICENSE.md", repository_url = "https://github.com/wikiti/pandoc-book-template" }
contents_file = "html/simple_book.html"


################
# HTML
################
# https://github.com/ashki23/pandoc-bootstrap is GPL 3.0 licensed

[[templates]]
description = "Bootstrap HTML template."
license = { name = "Apache 2.0", url = "https://github.com/tonyblundell/pandoc-bootstrap-template/blob/master/LICENSE", repository_url = "https://github.com/tonyblundell/pandoc-bootstrap-template" }
contents_file = "html/bootstrap.html"

# TODO: many CSS and JS files are loaded from the HTML with error
[[templates]]
description = "Bootstrap HTML with a sticky accordion menu template."
license = { name = "Apache 2.0", url = "https://github.com/diversen/pandoc-bootstrap-adaptive-template/blob/master/LICENSE", repository_url = "https://github.com/diversen/pandoc-bootstrap-adaptive-template" }
contents_file = "html/bootstrap_sticky_menu.html"

# https://github.com/diversen/pandoc-uikit uses UIKIT CSS and JS files, could be included but it doesn't seem right
# https://github.com/bitfragment/mindoc does not seem a great template
# https://github.com/tajmone/gh-themes-magick seems more adequate for static site generators
# https://github.com/tajmone/pandoc-goodies/tree/master/templates/html5/github has several licenses and it doesn't seem right for documents
# https://github.com/ryangrose/easy-pandoc-templates is GPL 3.0 licensed
