[package]
name = "mdbook-pandoc"
description = "Pandoc backend for mdBook"
keywords = ["mdbook", "pandoc", "epub", "pdf", "book", "gitbook", "rustbook", "markdown"]
license = "MPL-2.0"
repository = "https://github.com/Martin1887/mdbook-pandoc"
authors = ["Martin1887"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "*"