[[configs]]
description = "A clean pandoc LaTeX template for lecture notes and exercises with a focus on computer science."
contents_file = "configs/eisvogel.toml"

[[configs]]
description = "Template for making Tufte-style handouts."
contents_file = "configs/tufte_handouts.toml"

[[configs]]
description = "The Markdown resume. ConTeXt required."
contents_file = "configs/resume.toml"

[[configs]]
description = "Beamer slides and handouts by lmullen"
contents_file = "configs/lmullen_slides_handouts.toml"

[[configs]]
description = "A template for creating a PhD thesis in Pandoc."
contents_file = "configs/thesis_markdown.toml"

[[configs]]
description = "Template for PhD thesis used for submission to University College London."
contents_file = "configs/ucl_phd_thesis.toml"

[[configs]]
description = "Sound and versatile LaTeX template for academic articles."
contents_file = "configs/robusta.toml"

[[configs]]
description = "Sound and versatile LaTeX template for academic books."
contents_file = "configs/arabica.toml"

[[configs]]
description = "Simple APA 6 template."
contents_file = "configs/apa6.toml"

[[configs]]
description = "Template for exams"
contents_file = "configs/exam.toml"

[[configs]]
description = "Template for homework"
contents_file = "configs/homework.toml"

[[configs]]
description = "Template for lecture slides."
contents_file = "configs/lecture_beamer.toml"

[[configs]]
description = "AMSTAT journal."
contents_file = "configs/amstat.toml"

[[configs]]
description = "Biometrical journal."
contents_file = "configs/biometrical_journal.toml"

[[configs]]
description = "Biometrics journal."
contents_file = "configs/biometrics.toml"

[[configs]]
description = "Biometrika journal."
contents_file = "configs/biometrika.toml"

[[configs]]
description = "Biostatistics journal."
contents_file = "configs/biostatistics.toml"