################
# Everyday
################
[[resources]]
description = "The Markdown resume, HTML version."
version = "Unreleased 2020/01/26"
docs = "https://mszep.github.io/pandoc_resume"
dependencies = []
latex_packages = []
license = { name = "CC BY-SA 3.0", url = "https://creativecommons.org/licenses/by-sa/3.0/deed.en_US", repository_url = "https://github.com/mszep/pandoc_resume" }
contents_file = "include_in_header/resume.css.html"


################
# Professional/Academic
################
# TODO: convert fonts in variables
# TODO: a lot of problems (rare packages and chapters decorations don't work)
[[resources]]
description = "A template for creating a PhD thesis in Pandoc."
version = "Unreleased 2014/04/30"
docs = "(None)"
dependencies = []
latex_packages = ["quotchap", "threeparttable"]
license = { name = "UNLICENSE", url = "", repository_url = "https://github.com/chiakaivalya/thesis-markdown-pandoc" }
contents_file = "include_in_header/thesis_markdown.latex"

[[resources]]
description = "Template for PhD thesis used for submission to University College London."
version = "Unreleased 2021/01/30"
docs = "https://github.com/tompollard/phd_thesis_markdown/blob/master/README.md"
dependencies = ["python", "pandoc-fignos", "pandoc-eqnos", "pandoc-tablenos", "pandoc-secnos", "pandoc-shortcaption"]
latex_packages = ["truncate", "tocloft", "wallpaper", "morefloats", "sectsty", "siunitx", "threeparttable", "l3packages", "l3kernel", "l3experimental", "l3backend"]
license = { name = "MIT", url = "https://github.com/tompollard/phd_thesis_markdown/blob/master/LICENSE", repository_url = "https://github.com/tompollard/phd_thesis_markdown" }
contents_file = "include_in_header/ucl_phd_thesis_preamble.latex"
[[resources]]
description = "Template for PhD thesis used for submission to University College London."
version = "Unreleased 2021/01/30"
docs = "https://github.com/tompollard/phd_thesis_markdown/blob/master/README.md"
dependencies = ["python", "pandoc-fignos", "pandoc-eqnos", "pandoc-tablenos", "pandoc-secnos", "pandoc-shortcaption"]
latex_packages = []
license = { name = "MIT", url = "https://github.com/tompollard/phd_thesis_markdown/blob/master/LICENSE", repository_url = "https://github.com/tompollard/phd_thesis_markdown" }
contents_file = "include_in_header/ucl_phd_thesis.css.html"


# https://github.com/cagix/pandoc-lecture (exam, homework and lecture)
[[resources]]
description = "Template for exams."
version = "Unreleased 2022/08/30"
docs = "https://github.com/cagix/pandoc-lecture/blob/master/README.md"
dependencies = []
latex_packages = ["exam"]
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "include_in_header/exam_homework_lecture_definitions.latex"
[[resources]]
description = "Template for lecture slides."
version = "Unreleased 2022/08/30"
docs = "https://github.com/cagix/pandoc-lecture/blob/master/README.md"
dependencies = []
latex_packages = ["metropolis"]
license = { name = "MIT", url = "https://github.com/cagix/pandoc-lecture/blob/master/LICENSE.md", repository_url = "https://github.com/cagix/pandoc-lecture" }
contents_file = "include_in_header/lecture_beamer.latex"


# https://tex.stackexchange.com/questions/225736/latex-beamer-define-itemsep-globally
[[resources]]
description = "Bigger itemsep in each level of beamer slides."
version = "Unreleased"
docs = "https://tex.stackexchange.com/questions/225736/latex-beamer-define-itemsep-globally"
dependencies = []
latex_packages = ["xpatch"]
license = { name = "UNLICENSE", url = "", repository_url = "" }
contents_file = "include_in_header/beamer_itemsep.latex"